<?php
/** @var \HS\BannerSlider\Block\Adminhtml\Slider\AssignBanners $block */

/** @var \HS\BannerSlider\Block\Adminhtml\Slider\Tab\Banner $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="slider_banners" id="in_slider_banners" data-form-part="hs_banner_slider_slider_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "HS_BannerSlider/slider/assign-banners": {
                "selectedBanners": <?= /* @escapeNotVerified */ $block->getBannersJson() ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
